---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

dependencies:
  galaxy:
    collections:
      - { name: ansible.posix, version: 1.6.2 }
      - { name: ansible.utils, version: 5.1.2 }
      - { name: ansible.windows, version: 2.5.0 }
      - { name: chocolatey.chocolatey, version: 1.5.3 }
      - { name: community.general, version: 9.5.0 }
      - { name: community.windows, version: 2.3.0 }
      - { name: microsoft.ad, version: 1.7.1 }
  python:
    - requests-credssp>=2.0.0,<3.0.0

options:
  package_manager_path: /usr/bin/microdnf
