---
collections:
  - name: ansible.windows
    version: 1.14.0
  - name: community.windows
    version: 1.13.0
  - name: community.general
    version: 7.2.0
  - name: ansible.utils
    version: 2.10.3
  - name: ansible.posix
    version: 1.5.4
  - name: chocolatey.chocolatey
    version: 1.5.1
  - name: microsoft.ad
    version: 1.2.0
