---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

dependencies:
  galaxy:
    collections:
      - { name: ansible.utils, version: 5.1.2 }
      - { name: community.vmware, version: 5.0.1 }
      - { name: vmware.vmware_rest, version: 4.1.0 }
  python:
    - aiohttp==3.8.5
    - pyVmomi>=6.7
    - git+https://github.com/vmware/vsphere-automation-sdk-python.git ; python_version >= '2.7' # Python 2.6 is not supported

options:
  package_manager_path: /usr/bin/microdnf
