---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9@sha256:c6617b6b711eeab20b4b31a5259eac58d5244cd8f7b8ccb149847719677ee18f

dependencies:
  galaxy:
    collections:
      - { name: amazon.aws, version: 6.5.0 }
      - { name: azure.azcollection, version: 1.10.0 }
      - { name: community.aws, version: 6.3.0 }
      - { name: community.digitalocean, version: 1.26.0 }
      - { name: google.cloud, version: 1.2.0 }
      - { name: hetzner.hcloud, version: 4.0.1 }
      - { name: vultr.cloud, version: 1.10.0 }
  python:
    - awscli>=1.16.312

options:
  package_manager_path: /usr/bin/microdnf
