---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

dependencies:
  galaxy:
    collections:
      - { name: amazon.aws, version: 6.5.0 }
      - { name: azure.azcollection, version: 1.10.0 }
      - { name: cloud.terraform, version: 3.0.0 }
      - { name: community.aws, version: 6.3.0 }
      - { name: community.digitalocean, version: 1.24.0 }
      - { name: google.cloud, version: 1.2.0 }
      - { name: hetzner.hcloud, version: 1.16.0 }
      - { name: vultr.cloud, version: 1.10.0 }
  python:
    - awscli>=1.16.312

additional_build_steps:
  prepend_final:
    - RUN /usr/bin/microdnf install -y yum-utils
    - RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - RUN /usr/bin/microdnf install -y terraform

options:
  package_manager_path: /usr/bin/microdnf
