---
collections:
  - name: ansible.netcommon
    version: 5.1.2
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.10.3
  - name: arista.eos
    version: 6.0.1
  - name: cisco.asa
    version: 4.0.1
  - name: cisco.ios
    version: 4.6.1
  - name: cisco.iosxr
    version: 5.0.3
  - name: cisco.nxos
    version: 4.4.0
  - name: community.network
    version: 5.0.0
  - name: community.routeros
    version: 2.8.3
  - name: frr.frr
    version: 2.0.2
  - name: junipernetworks.junos
    version: 5.2.0
  - name: vyos.vyos
    version: 4.1.0
