---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest

dependencies:
  galaxy:
    collections:
      - { name: netbox.netbox, version: 3.21.0 }
  python:
    - pynetbox
    - packaging
    - pytz

options:
  package_manager_path: /usr/bin/microdnf
