---
name: "Get changes to execution environments"

on:
  workflow_call:
    outputs:
      addedOrModified:
        description: "List of added or modified files"
        value: ${{ jobs.get-changes.outputs.addedOrModified }}
      addedOrModifiedImages:
        description: "List of added or modified execution environments"
        value: ${{ jobs.get-changes.outputs.addedOrModifiedImages }}

jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      addedOrModified: "${{ steps.filter.outputs.addedOrModified }}"
      addedOrModifiedImages: "${{ steps.filter-environments.outputs.addedOrModifiedImages }}"
    steps:
      - uses: actions/checkout@v4
      - name: "Collect changed files"
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            addedOrModified:
              - added|modified: 'environments/*/**'
      - name: "Determined the environments that were changed"
        if: ${{ steps.filter.outputs.addedOrModified == 'true' }}
        id: filter-environments
        run: |
          PATHS='${{ steps.filter.outputs.addedOrModified_files }}'
          OUTPUT=$(echo $PATHS | jq --raw-output -c 'map(. |= split("/")[1]) | unique | join(",")')
          echo "addedOrModifiedImages=${OUTPUT}" >> $GITHUB_OUTPUT
